In [2]:
import torch
import numpy as np

6.3.1 基本张量创建

（1）按内容创建张量

In [3]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [4]:
# 传入一个一维数组
tensor2 = torch.tensor([1.0, 2, 3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [5]:
# 传入一个二维ndarray
tensor3 = torch.tensor(np.array([[1.0, 2, 3], [4, 5, 6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.Size([2, 3])
torch.float64


(2)创建指定形状的张量

In [10]:
tensor1 = torch.Tensor(3, 2, 4) # 底层是 2 * 4 的矩阵，一个 3 个
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[6.6933e+32, 7.3288e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [11]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [12]:
tensor2 = torch.Tensor(np.array([[1, 2, 3, 4], [4, 5, 6, 7]]))
print(tensor2)
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.float32


In [15]:
tensor1 = torch.Tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
torch.float32


(3) 创建指定类型的张量

In [17]:
# int（int32）类型
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int32


In [18]:
# long（int64）类型
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


In [19]:
# short（int16）类型
tensor1 = torch.ShortTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int16)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int16
torch.int16


In [21]:
tensor1 = torch.ByteTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int8)
print(tensor1.dtype)
print(tensor2.dtype)

torch.uint8
torch.int8


In [25]:
# float类型
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.float32
torch.float32
tensor([[6.5925e+32, 7.3288e-43, 0.0000e+00],
        [2.0000e+00, 0.0000e+00, 2.1250e+00]])


In [26]:
# double类型
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.float64
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [27]:
# half类型
tensor1 = torch.HalfTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.float16
torch.float16
tensor([[0.0000, 0.0000, 0.0000],
        [2.0156, 0.0000, 2.1250]], dtype=torch.float16)


In [28]:
# bool类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.bool
torch.bool
tensor([[True, True, True],
        [True, True, True]])


6.3.2 指定区间的张量创建

In [29]:
tensor1 = torch.arange(10, 30, 2)
print(tensor1)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


In [30]:
tensor2 = torch.arange(6)
print(tensor2)

tensor([0, 1, 2, 3, 4, 5])


In [32]:
tensor1 = torch.linspace(10, 30, 6)
print(tensor1)

tensor([10., 14., 18., 22., 26., 30.])


In [33]:
tensor1 = torch.logspace(1, 3, 3, base=2)
print(tensor1)

tensor([2., 4., 8.])


6.3.3 按数值填充张量

In [35]:
tensor1 = torch.zeros(2, 3)
print(tensor1)
print(tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [36]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [39]:
tensor1 = torch.full((3,2), 6.5)
print(tensor1)
print(tensor1.dtype)

tensor([[6.5000, 6.5000],
        [6.5000, 6.5000],
        [6.5000, 6.5000]])
torch.float32


In [40]:
tensor2 = torch.empty_like(tensor1)
print(tensor2)

tensor([[6.5930e+32, 7.3288e-43],
        [0.0000e+00, 2.0000e+00],
        [0.0000e+00, 2.1250e+00]])


In [41]:
tensor1 = torch.eye(3)
print(tensor1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [42]:
tensor1 = torch.eye(3, 5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


6.3.4 随机张量创建

In [43]:
tensor1 = torch.rand(2, 3)
print(tensor1)

tensor([[0.5580, 0.3298, 0.9921],
        [0.6001, 0.6594, 0.3856]])


In [44]:
tensor2 = torch.rand_like(tensor1)
print(tensor2)

tensor([[0.5045, 0.7364, 0.7347],
        [0.2194, 0.0922, 0.9563]])


In [45]:
tensor1 = torch.randint(low=0, high=100, size=(2, 3))
print(tensor1)

tensor([[96, 21, 73],
        [33, 57, 23]])


In [46]:
tensor2 = torch.randint_like(tensor1, low=10, high=20)
print(tensor2)

tensor([[10, 18, 17],
        [15, 16, 12]])


In [48]:
tensor1 = torch.randn(4, 2)
print(tensor1)

tensor([[ 1.1655, -1.4741],
        [ 0.6994, -0.0043],
        [ 0.0419,  0.6164],
        [-0.3374, -0.5580]])


In [49]:
tensor2 = torch.randn_like(tensor1)
print(tensor2)

tensor([[-1.1710, -0.5159],
        [-0.8019, -1.8273],
        [ 0.9732,  0.1992],
        [ 0.8585, -0.2739]])


In [50]:
tensor1 = torch.normal(5, 2, tensor2.shape)
print(tensor1)

tensor([[ 3.9298,  8.7393],
        [ 6.6812,  4.9145],
        [ 5.6504,  6.5016],
        [ 3.6267, -1.8570]])


In [52]:
# 随机重新排列
tensor1 = torch.randperm(10)
print(tensor1)

tensor([1, 3, 2, 5, 4, 9, 7, 0, 6, 8])


In [55]:
# 查看和指定随机数种子
print(torch.random.initial_seed())

1078833928692500


In [56]:
torch.manual_seed(42)

In [57]:
print(torch.random.initial_seed())

42
