In [29]:
import torch

In [30]:
tensor1 = torch.randint(1, 10, (3, 2, 4)).float()
print(tensor1)

tensor([[[2., 3., 1., 4.],
         [7., 5., 9., 7.]],

        [[3., 8., 6., 3.],
         [1., 4., 1., 8.]],

        [[2., 1., 7., 1.],
         [1., 8., 2., 6.]]])


In [31]:
# sum 求和
print(tensor1.sum())

tensor(100.)


In [32]:
print(tensor1.sum(dim=2))

tensor([[10., 28.],
        [20., 14.],
        [11., 17.]])


In [33]:
# mean 求均值
print(tensor1.mean())

tensor(4.1667)


In [34]:
print(tensor1.mean(dim=2))

tensor([[2.5000, 7.0000],
        [5.0000, 3.5000],
        [2.7500, 4.2500]])


In [35]:
# std 求标准方差
print(tensor1.std())

tensor(2.7767)


In [36]:
# max、min求最大最小值
print(tensor1.max())

tensor(9.)


In [37]:
print(tensor1.min(dim=2))

torch.return_types.min(
values=tensor([[1., 5.],
        [3., 1.],
        [1., 1.]]),
indices=tensor([[2, 1],
        [0, 0],
        [1, 0]]))


In [38]:
print(tensor1.argmax())

tensor(6)


In [41]:
# 去重
print(tensor1.unique())

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [46]:
# 排序
print(tensor1.sort())

torch.return_types.sort(
values=tensor([[[1., 2., 3., 4.],
         [5., 7., 7., 9.]],

        [[3., 3., 6., 8.],
         [1., 1., 4., 8.]],

        [[1., 1., 2., 7.],
         [1., 2., 6., 8.]]]),
indices=tensor([[[2, 0, 1, 3],
         [1, 0, 3, 2]],

        [[0, 3, 2, 1],
         [0, 2, 1, 3]],

        [[1, 3, 0, 2],
         [0, 2, 3, 1]]]))
