In [2]:
import torch

In [3]:
tensor1 = torch.randint(1, 10, (2, 3, 6))
print(tensor1)

tensor([[[2, 9, 2, 1, 4, 1],
         [6, 3, 3, 8, 2, 7],
         [9, 3, 8, 9, 1, 7]],

        [[3, 5, 3, 5, 6, 6],
         [8, 9, 4, 3, 2, 9],
         [5, 4, 4, 9, 7, 3]]])


6.8.1 交换维度

In [4]:
# 1. 交换两个维度
print(tensor1.transpose(0, 2))

tensor([[[2, 3],
         [6, 8],
         [9, 5]],

        [[9, 5],
         [3, 9],
         [3, 4]],

        [[2, 3],
         [3, 4],
         [8, 4]],

        [[1, 5],
         [8, 3],
         [9, 9]],

        [[4, 6],
         [2, 2],
         [1, 7]],

        [[1, 6],
         [7, 9],
         [7, 3]]])


In [5]:
# 2. 重新排列多个维度
print(tensor1.permute(0, 2, 1))

tensor([[[2, 6, 9],
         [9, 3, 3],
         [2, 3, 8],
         [1, 8, 9],
         [4, 2, 1],
         [1, 7, 7]],

        [[3, 8, 5],
         [5, 9, 4],
         [3, 4, 4],
         [5, 3, 9],
         [6, 2, 7],
         [6, 9, 3]]])


6.8.2 调整形状

In [6]:
# 1. reshape
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1.shape)
print(tensor1)

torch.Size([3, 5, 4])
tensor([[[1, 4, 5, 6],
         [5, 7, 1, 7],
         [7, 3, 7, 4],
         [2, 8, 9, 7],
         [2, 6, 6, 1]],

        [[6, 6, 2, 1],
         [7, 8, 5, 8],
         [4, 3, 2, 7],
         [2, 7, 8, 3],
         [6, 9, 1, 9]],

        [[3, 9, 1, 7],
         [4, 3, 5, 6],
         [6, 2, 1, 6],
         [9, 4, 1, 1],
         [5, 5, 7, 5]]])


In [7]:
print(tensor1.reshape(6, 10))

tensor([[1, 4, 5, 6, 5, 7, 1, 7, 7, 3],
        [7, 4, 2, 8, 9, 7, 2, 6, 6, 1],
        [6, 6, 2, 1, 7, 8, 5, 8, 4, 3],
        [2, 7, 2, 7, 8, 3, 6, 9, 1, 9],
        [3, 9, 1, 7, 4, 3, 5, 6, 6, 2],
        [1, 6, 9, 4, 1, 1, 5, 5, 7, 5]])


In [8]:
print(tensor1.reshape(3, -1))

tensor([[1, 4, 5, 6, 5, 7, 1, 7, 7, 3, 7, 4, 2, 8, 9, 7, 2, 6, 6, 1],
        [6, 6, 2, 1, 7, 8, 5, 8, 4, 3, 2, 7, 2, 7, 8, 3, 6, 9, 1, 9],
        [3, 9, 1, 7, 4, 3, 5, 6, 6, 2, 1, 6, 9, 4, 1, 1, 5, 5, 7, 5]])


In [9]:
print(tensor1.reshape(-1))

tensor([1, 4, 5, 6, 5, 7, 1, 7, 7, 3, 7, 4, 2, 8, 9, 7, 2, 6, 6, 1, 6, 6, 2, 1,
        7, 8, 5, 8, 4, 3, 2, 7, 2, 7, 8, 3, 6, 9, 1, 9, 3, 9, 1, 7, 4, 3, 5, 6,
        6, 2, 1, 6, 9, 4, 1, 1, 5, 5, 7, 5])


In [10]:
# 2. view
print(tensor1.is_contiguous())

True


In [11]:
print(tensor1.view(-1, 10))

tensor([[1, 4, 5, 6, 5, 7, 1, 7, 7, 3],
        [7, 4, 2, 8, 9, 7, 2, 6, 6, 1],
        [6, 6, 2, 1, 7, 8, 5, 8, 4, 3],
        [2, 7, 2, 7, 8, 3, 6, 9, 1, 9],
        [3, 9, 1, 7, 4, 3, 5, 6, 6, 2],
        [1, 6, 9, 4, 1, 1, 5, 5, 7, 5]])


In [12]:
print(tensor1.shape)

torch.Size([3, 5, 4])


In [13]:
# 对张量进行转置操作，让内存空间不连续
tensor1 = tensor1.permute(2,1,0)
print(tensor1.shape)

torch.Size([4, 5, 3])


In [14]:
print(tensor1.is_contiguous())

False


In [15]:
print(tensor1.contiguous().view(-1, 10))

tensor([[1, 6, 3, 5, 7, 4, 7, 4, 6, 2],
        [2, 9, 2, 6, 5, 4, 6, 9, 7, 8],
        [3, 3, 3, 2, 8, 7, 4, 6, 9, 5],
        [5, 2, 1, 1, 5, 5, 7, 2, 1, 9],
        [8, 1, 6, 1, 7, 6, 1, 7, 7, 8],
        [6, 4, 7, 6, 7, 3, 1, 1, 9, 5]])


6.8.3 增加或删除维度

In [16]:
# 1. 增加维度
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)

tensor([1, 2, 3])


In [17]:
# 在 0 维上增加一个维度，1×3
print(tensor1.unsqueeze(dim=0))

tensor([[1, 2, 3]])


In [18]:
# 在 1 维上增加一个维度，3×1
print(tensor1.unsqueeze(dim=-1))
print(tensor1)

tensor([[1],
        [2],
        [3]])
tensor([1, 2, 3])


In [19]:
print(tensor1.unsqueeze_(dim=-2))
print(tensor1)

tensor([[1, 2, 3]])
tensor([[1, 2, 3]])


In [20]:
# 2. 减少维度
print(tensor1.squeeze(dim=0))

tensor([1, 2, 3])


6.9 张量拼接操作

In [21]:
# 1. 拼接
tensor1 = torch.randint(1, 10, (2, 2, 5))
tensor2 = torch.randint(1, 10, (2, 3, 5))
print(tensor1)
print(tensor2)

tensor([[[7, 6, 4, 9, 3],
         [3, 8, 2, 3, 2]],

        [[3, 6, 8, 3, 6],
         [2, 4, 5, 9, 2]]])
tensor([[[8, 5, 1, 7, 6],
         [5, 2, 7, 4, 9],
         [7, 8, 5, 5, 7]],

        [[4, 3, 2, 8, 2],
         [6, 1, 7, 5, 8],
         [3, 2, 4, 9, 5]]])


In [22]:
print(torch.cat((tensor1, tensor2), dim=1))

tensor([[[7, 6, 4, 9, 3],
         [3, 8, 2, 3, 2],
         [8, 5, 1, 7, 6],
         [5, 2, 7, 4, 9],
         [7, 8, 5, 5, 7]],

        [[3, 6, 8, 3, 6],
         [2, 4, 5, 9, 2],
         [4, 3, 2, 8, 2],
         [6, 1, 7, 5, 8],
         [3, 2, 4, 9, 5]]])


In [23]:
# 2. 堆叠
tensor1 = torch.randint(1, 10, (4, 3, 5))
tensor2 = torch.randint(1, 10, (4, 3, 5))
print(tensor1)
print(tensor2)

tensor([[[1, 1, 3, 2, 1],
         [5, 9, 6, 7, 8],
         [6, 2, 5, 7, 6]],

        [[4, 4, 7, 9, 4],
         [6, 8, 8, 8, 7],
         [1, 9, 9, 4, 6]],

        [[5, 2, 9, 2, 5],
         [9, 1, 4, 7, 3],
         [5, 4, 9, 6, 1]],

        [[5, 5, 9, 5, 1],
         [5, 6, 2, 2, 2],
         [2, 9, 9, 3, 9]]])
tensor([[[8, 4, 1, 3, 1],
         [7, 7, 7, 1, 1],
         [7, 4, 8, 9, 9]],

        [[4, 2, 8, 4, 8],
         [1, 5, 1, 1, 5],
         [9, 7, 9, 8, 3]],

        [[7, 6, 2, 1, 9],
         [9, 7, 4, 7, 9],
         [1, 7, 3, 4, 3]],

        [[9, 3, 5, 7, 6],
         [9, 5, 8, 5, 5],
         [3, 5, 8, 9, 9]]])


In [26]:
tensor3 = torch.stack([tensor1, tensor2], dim=0)
print(tensor3)
print(tensor3.shape)

tensor([[[[1, 1, 3, 2, 1],
          [5, 9, 6, 7, 8],
          [6, 2, 5, 7, 6]],

         [[4, 4, 7, 9, 4],
          [6, 8, 8, 8, 7],
          [1, 9, 9, 4, 6]],

         [[5, 2, 9, 2, 5],
          [9, 1, 4, 7, 3],
          [5, 4, 9, 6, 1]],

         [[5, 5, 9, 5, 1],
          [5, 6, 2, 2, 2],
          [2, 9, 9, 3, 9]]],


        [[[8, 4, 1, 3, 1],
          [7, 7, 7, 1, 1],
          [7, 4, 8, 9, 9]],

         [[4, 2, 8, 4, 8],
          [1, 5, 1, 1, 5],
          [9, 7, 9, 8, 3]],

         [[7, 6, 2, 1, 9],
          [9, 7, 4, 7, 9],
          [1, 7, 3, 4, 3]],

         [[9, 3, 5, 7, 6],
          [9, 5, 8, 5, 5],
          [3, 5, 8, 9, 9]]]])
torch.Size([2, 4, 3, 5])


In [25]:
tensor3 = torch.stack([tensor1, tensor2], dim=3)
print(tensor3.shape)
print(tensor3)

torch.Size([4, 3, 5, 2])
tensor([[[[1, 8],
          [1, 4],
          [3, 1],
          [2, 3],
          [1, 1]],

         [[5, 7],
          [9, 7],
          [6, 7],
          [7, 1],
          [8, 1]],

         [[6, 7],
          [2, 4],
          [5, 8],
          [7, 9],
          [6, 9]]],


        [[[4, 4],
          [4, 2],
          [7, 8],
          [9, 4],
          [4, 8]],

         [[6, 1],
          [8, 5],
          [8, 1],
          [8, 1],
          [7, 5]],

         [[1, 9],
          [9, 7],
          [9, 9],
          [4, 8],
          [6, 3]]],


        [[[5, 7],
          [2, 6],
          [9, 2],
          [2, 1],
          [5, 9]],

         [[9, 9],
          [1, 7],
          [4, 4],
          [7, 7],
          [3, 9]],

         [[5, 1],
          [4, 7],
          [9, 3],
          [6, 4],
          [1, 3]]],


        [[[5, 9],
          [5, 3],
          [9, 5],
          [5, 7],
          [1, 6]],

         [[5, 9],
          [6, 5],
          [2,